projects:
  postsactivityamplify:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: yrt53loec5aclcvoqkf7cs3bsm
      endpoints:
        prod: >-
          https://odkc36fxlffwja7gmau2jesj3u.appsync-api.eu-west-1.amazonaws.com/graphql
